### ISSUE TITLE
Incomplete `requirements.txt`

### ISSUE THREAD

**Issue by mykolaskrynnyk** [UNDP-Data/dsc-energy-ai-backend#5]
Some required packages are missing from [requirements.txt](https://github.com/UNDP-Data/dsc-energy-ai-backend/blob/main/requirements.txt). There are additional packages installed in [Dockerfile](https://github.com/UNDP-Data/dsc-energy-ai-backend/blob/main/Dockerfile). For deployment, all packages need to be specified in `requirements.txt`.

- [ ] Packages from `Dockerfile` need to be moved to `requirements.txt`.
- [ ] All packages should have at least some kind of version constraints. Core packages may need to be pinned.
- [ ] `spaCy` models need to be specified in `requirements.txt` too. See an example [here](https://stackoverflow.com/a/61702528).
- [ ] `Dockerfile` should be updated accordingly.

**Comment by davolu** [comment]
All libraries have been moved to requirements.txt

It’s advisable to create a virtual environments (optional but recommended)

E.g 
**python3.9 -m venv myenv
source myenv/bin/activate**

Then install dependencies 

**pip install -r requirements.txt**

Run this once to install spacy english data on the environment 

 **python3.9 -m spacy download en**


Finally run the file : 

**python3.9 main.py** 


Depending on the devOps preference can use services like pm2, forever, nohup etc to make it run in background.

**Comment by mykolaskrynnyk** [comment]
@davolu , the above issues have not been properly addressed. `langchain` version must be pinned, `spaCy` model is still missing from the `requirements.txt` and so on.

**Comment by davolu** [comment]
@mykolaskrynnyk  thanks for the feedback. 
The langchain version has been pined as requested. 
spaCy model can't be added to the requirements.txt normally. Its a url file download and not a library. 
The command will need to be ran just once to download the file to on the python enviroment: **python3.9 -m spacy download en**

Another alternative is it can be add to a script either a bash or py and ran once to download the model. Let me know if anything else and I'd implement if possible.

Thanks.
